/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Products
         * @description Search the product catalog by text and/or category.
         *
         *     Returns a list of matching products.
         */
        get: operations["search_products_api_catalog_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/outcome": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Outcome
         * @description Process a natural-language outcome into a grocery cart.
         */
        post: operations["create_outcome_api_outcome_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/intent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Voice Intent
         * @description Route a voice transcript through the outcome engine (mode=TEXT).
         */
        post: operations["voice_intent_api_voice_intent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/constraint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Constraint Cart
         * @description Build a cart constrained to the given budget.
         */
        post: operations["constraint_cart_api_constraint_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vision/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Image
         * @description Analyze an uploaded image (or placeholder text) and build a cart.
         *
         *     For now routes through the outcome engine with mode=PHOTO.
         *     The mock provider returns deterministic results regardless of input.
         */
        post: operations["analyze_image_api_vision_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/share/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse Share
         * @description Parse a shared recipe link or text and build a cart.
         */
        post: operations["parse_share_api_share_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cart/op": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cart Operation
         * @description Execute a cart operation (add, remove, update, total).
         */
        post: operations["cart_operation_api_cart_op_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cart/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cart
         * @description Retrieve a cart by session ID.
         */
        get: operations["get_cart_api_cart__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sos Cart
         * @description Build an emergency kit cart from a situation description.
         */
        post: operations["sos_cart_api_sos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stock Override
         * @description Override the stock status of a product (demo control).
         *
         *     Sets a cache override that takes priority over the product record.
         *     Also updates the product record in the repository for consistency.
         */
        post: operations["stock_override_api_admin_stock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_analyze_image_api_vision_analyze_post */
        Body_analyze_image_api_vision_analyze_post: {
            /** File */
            file?: string | null;
        };
        /** CartItemResponse */
        CartItemResponse: {
            /** Product Id */
            product_id: string;
            /** Name */
            name: string;
            /**
             * Brand
             * @default
             */
            brand: string;
            /**
             * Price
             * @default 0
             */
            price: number;
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
            /**
             * Unit
             * @default
             */
            unit: string;
            /**
             * Line Total
             * @default 0
             */
            line_total: number;
            /**
             * Reason
             * @default
             */
            reason: string;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /** Substituted For */
            substituted_for?: string | null;
        };
        /**
         * CartOpRequest
         * @description Voice/UI follow-up cart operation (A2 follow-ups).
         */
        CartOpRequest: {
            /** Session Id */
            session_id: string;
            /**
             * Op
             * @description add | remove | update | total
             */
            op: string;
            /**
             * Entity
             * @description product name or id the op targets
             */
            entity?: string | null;
            /** Quantity */
            quantity?: number | null;
        };
        /**
         * CartResponse
         * @description The primary response shape returned by every front door.
         */
        CartResponse: {
            /** Session Id */
            session_id: string;
            /** Items */
            items?: components["schemas"]["CartItemResponse"][];
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Currency
             * @default INR
             */
            currency: string;
            /**
             * Mode
             * @default text
             */
            mode: string;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /** Substitutions */
            substitutions?: components["schemas"]["SubstitutionResponse"][];
            /** Notes */
            notes?: string[];
            /** Clarification */
            clarification?: string | null;
            /** Reasoning Trail */
            reasoning_trail?: string[];
            /** Budget */
            budget?: number | null;
            /** Remaining Budget */
            remaining_budget?: number | null;
            /** Shortfall */
            shortfall?: number | null;
            /** Eta Minutes */
            eta_minutes?: number | null;
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
        };
        /**
         * ConstraintRequest
         * @description A3 — constraint-first ordering.
         */
        ConstraintRequest: {
            /**
             * Budget
             * @description budget cap in INR
             */
            budget: number;
            /** Servings */
            servings: number;
            /**
             * Text
             * @description optional outcome hint, e.g. 'dinner'
             */
            text?: string | null;
            /** Session Id */
            session_id?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /**
             * Service
             * @default nowcart
             */
            service: string;
            /**
             * Version
             * @default 0.1.0
             */
            version: string;
        };
        /** OkResponse */
        OkResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /**
         * OutcomeRequest
         * @description A1 / generic text outcome.
         */
        OutcomeRequest: {
            /**
             * Text
             * @description e.g. 'I'm making Biryani for 4'
             */
            text: string;
            /**
             * Servings
             * @description optional serving count for scaling
             */
            servings?: number | null;
            /** Session Id */
            session_id?: string | null;
        };
        /**
         * ShareRequest
         * @description B4 — shared recipe link or pasted recipe text.
         */
        ShareRequest: {
            /** Url */
            url?: string | null;
            /** Text */
            text?: string | null;
            /** Session Id */
            session_id?: string | null;
        };
        /**
         * SosRequest
         * @description D4 — emergency mode.
         */
        SosRequest: {
            /**
             * Situation
             * @description e.g. 'guests in 30 minutes'
             */
            situation: string;
            /** Session Id */
            session_id?: string | null;
        };
        /**
         * StockOverrideRequest
         * @description Demo control to force a product in/out of stock (Requirement 8.3).
         */
        StockOverrideRequest: {
            /** Product Id */
            product_id: string;
            /** In Stock */
            in_stock: boolean;
        };
        /** SubstitutionResponse */
        SubstitutionResponse: {
            /** Original Product Id */
            original_product_id: string;
            /** Original Name */
            original_name: string;
            /** Substitute Product Id */
            substitute_product_id: string;
            /** Substitute Name */
            substitute_name: string;
            /** Reason */
            reason: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VoiceIntentRequest
         * @description A2 — a speech transcript routed through the same pipeline as text.
         */
        VoiceIntentRequest: {
            /** Transcript */
            transcript: string;
            /** Session Id */
            session_id?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    search_products_api_catalog_search_get: {
        parameters: {
            query?: {
                /** @description Text search query */
                q?: string | null;
                /** @description Category filter */
                category?: string | null;
                /** @description Max results */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_outcome_api_outcome_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutcomeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    voice_intent_api_voice_intent_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoiceIntentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    constraint_cart_api_constraint_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConstraintRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_image_api_vision_analyze_post: {
        parameters: {
            query?: {
                text?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_image_api_vision_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_share_api_share_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cart_operation_api_cart_op_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CartOpRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cart_api_cart__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sos_cart_api_sos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SosRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_override_api_admin_stock_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockOverrideRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
